# site settings
title: Hawaiian Pizza
email: admin@hawaiianpizza.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Learn how to make Hawaiian Pizza and find the world's best Hawaiian Pizza near you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hawaiianpizza.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:path
image: /assets/images/hawaiianpizza-default-image.jpg

# build settings
markdown: kramdown
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
exclude:
 - Gemfile.lock

# jekyll-seo-tag config
twitter:
#  username: hawaiianpizza
#  card: summary_large_image
#facebook:
  # app_id: 1234
  #publisher: 1234
  #admins: 1234
social:
  name: Hawaiian Pizza
  links:
    - https://www.hawaiianpizza.co.uk
#webmaster_verifications:
  #google: 1234
  #bing: 1234
  #alexa: 1234
  #yandex: 1234
  #baidu: 1234
gtm: G-MLRDXBXMCM

# site defaults 
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/hawaiianpizza-default-image.jpg